Rollup latest testing updates into main (#434)
* Add Mystic BBS support with custom RetroNAS filebases [sairuk]
* Add Netatalk4 support [sairuk]
* Add a set of general linux troubleshooting tools [sairuk]
* Add additional missing user/group message prompt [sairuk]
* Add experimental xbox share for use with project stella [sairuk]
* Add helper script for generating a changelog [sairuk]
* Add helper script to re-index (install) menu [sairuk]
* Add local tool documentation [sairuk]
* Add mTCP-Netdrive support [sairuk]
* Add retro-aim-server support [sairuk]
* Fix for #433, ps3netsrv rolled out to all installers [sairuk]
* Fix for Dialog display [sairuk]
* Fix for NABU installer [sairuk]
* Fix for ethflopd, sourceforge pointing to dos download #432 [sairuk]
* Fix for the dexdrive installer [sairuk]
* Fix for wifi [sairuk]
* Fix hostapd_cli connect [sairuk]
* Promote tools out of experimental [sairuk]
* Remove term selection delay on startup [sairuk]
* Update hb-store-cdn to the binary release, now x86 only [sairuk]
* Updated menus, restructure menus, move services and tools menus to submenus of the applicable installer [sairuk]
* Updated supported systems [sairuk]

diff --git a/ansible/templates/install_ethflopd/install_ethflopd.sh.j2 b/ansible/templates/install_ethflopd/install_ethflopd.sh.j2
--- a/ansible/templates/install_ethflopd/install_ethflopd.sh.j2
+++ b/ansible/templates/install_ethflopd/install_ethflopd.sh.j2
@@ -3,18 +3,21 @@
 SRCDIR="{{ retronas_root }}/src"
 BINDIR="{{ retronas_root }}/bin"
 APPNAME=ethflopd
+VERSION=20240916
 
 echo "Configuring build directories..."
 rm -rf "${SRCDIR}"
-mkdir -p "${SRCDIR}"
+mkdir -p "${SRCDIR}/${APPNAME}"
 cd "${SRCDIR}"
 
 echo "Downloading ethflopd source..."
-curl -L -o ${APPNAME}.zip https://sourceforge.net/projects/ethflop/files/latest/download
-unzip ${APPNAME}.zip -d ${APPNAME}
+curl -L -o ${APPNAME}.tar.gz https://master.dl.sourceforge.net/project/ethflop/ethflopd%20%28server%29/${VERSION}/ethflopd-${VERSION}-src.tar.gz
+tar -xvf ${APPNAME}.tar.gz -C ${APPNAME}
 
 cd ${APPNAME}
-make
+
+[ ! -f Makefile.linux ] && echo "Makefile not found, cannot build" && exit 1
+make -f Makefile.linux
 
 echo "Moving binary to bindir..."
 mv -vf ${APPNAME} "${BINDIR}"/
