Add fixes to hdparm.sh, no drive present, cannot read maxsectors etc

diff --git a/ansible/templates/install_hdparm/hdparm.sh.j2 b/ansible/templates/install_hdparm/hdparm.sh.j2
--- a/ansible/templates/install_hdparm/hdparm.sh.j2
+++ b/ansible/templates/install_hdparm/hdparm.sh.j2
@@ -8,7 +8,6 @@ NOSLEEP=(
   /dev/sda
 )
 
-
 # REQUIREMENTS
 REQFAIL=0
 [ ! -x /usr/sbin/hdparm ] && echo "hdparm not executable" && REQFAIL=1
@@ -18,8 +17,10 @@ REQFAIL=0
 
 for DISK in ${NOSLEEP[@]}
 do
+        [ ! -r $DISK ] && echo "$DISK is not readable, exiting" && exit 1
         MAXSECTOR=$(hdparm -I $DISK | awk '/LBA48/{print $5}')
+        [ -z $MAXSECTOR ] && echo "Cannot obtain MAXSECTORS from $DISK, exiting" && exit 1
         RANDSECTOR=$(shuf -i 1-${MAXSECTOR} -n 1)
         echo "Reading ${RANDSECTOR} (max:${MAXSECTOR}) from ${DISK}"
-        hdparm --readsector $RANDSECTOR $DISK &>/dev/null
+        hdparm --read-sector $RANDSECTOR $DISK &>/dev/null
 done
