Add workaround for raspios gnu tools without lfs support

diff --git a/ansible/templates/install_hdparm/hdparm.sh.j2 b/ansible/templates/install_hdparm/hdparm.sh.j2
--- a/ansible/templates/install_hdparm/hdparm.sh.j2
+++ b/ansible/templates/install_hdparm/hdparm.sh.j2
@@ -3,6 +3,28 @@
 # Prevent a disk going to sleep by reading a sector
 #
 
+TRIES=0
+RANDSECTOR=1
+
+function set_sector() {
+  local MAXSECTOR=$1
+  RANDSECTOR=$(shuf -i 1-${MAXSECTOR} -n 1 2>&1)
+
+
+  # test to see if the above was successful, can fail on systems without lfs compiled
+  # see https://www.gnu.org/software/coreutils/faq/coreutils-faq.html
+       
+  if [ $? -ne 0 ]
+  then
+    echo "Failed to determine randsec at $MAXSECTOR ($TRIES/$RETRY)"
+    [ $TRIES -eq 3 ] && RANDSECTOR=1 && exit
+    MAXSECTOR=$((${MAXSECTOR}/2))
+    TRIES=$((${TRIES}+1))
+    set_sector $MAXSECTOR
+  fi
+
+}
+
 # list the drives that need to be punished
 NOSLEEP=(
   /dev/sda
@@ -20,7 +42,14 @@ do
         BLOCKDEV=$(echo $DISK | sed 's/\/dev\///')
         MAXSECTOR=$(cat /sys/class/block/${BLOCKDEV}/size)
         [ -z $MAXSECTOR ] && echo "Cannot obtain MAXSECTORS from $DISK, exiting" && exit 1
-        RANDSECTOR=$(shuf -i 1-${MAXSECTOR} -n 1)
-        echo "Reading ${RANDSECTOR} (max:${MAXSECTOR}) from ${DISK}"
-        hdparm --read-sector $RANDSECTOR $DISK &>/dev/null
+        
+        set_sector $MAXSECTOR
+
+        if [ ! -z "${RANDSECTOR}" ]
+        then
+          echo "Reading ${RANDSECTOR} (max:${MAXSECTOR}) from ${DISK}"
+          hdparm --read-sector $RANDSECTOR $DISK &>/dev/null
+        else
+          echo "Failed to obtain a random sector is the drive available?" 
+        fi
 done
