Testing (#445)
note supported dreampi version [sairuk]
exit if build fails [sairuk]
start up speed tweaks [sairuk]
increase menu generation performance [sairuk]
report ancestor commit, because its not in the path [sairuk]
additional dep for netatalk4 [sairuk]
implement netatalk4 changes to readme as per rdmark in #442 [sairuk]
ps3netsrv compile fix for #441 [sairuk]

diff --git a/ansible/templates/install_ps3netsrv/install_ps3netsrv.sh.j2 b/ansible/templates/install_ps3netsrv/install_ps3netsrv.sh.j2
--- a/ansible/templates/install_ps3netsrv/install_ps3netsrv.sh.j2
+++ b/ansible/templates/install_ps3netsrv/install_ps3netsrv.sh.j2
@@ -22,15 +22,22 @@ echo $SOURCECODE
 #curl -OJL "https://github.com/${SOURCECODE}"
 curl -OJL "${SOURCECODE}"
 unzip ps3netsrv*.zip
-cd ps3netsrv*/ps3netsrv
+cd ps3netsrv*/src
 meson buildrelease --buildtype=release
 ninja -C buildrelease
 
-echo "Moving binary to RetroNAS bin dir..."
-mkdir -p "${BINDIR}" 2>/dev/null
-mv -vf buildrelease/ps3netsrv "${BINDIR}"/
+if [ $? -eq 0 ]
+then
+  echo "Moving binary to RetroNAS bin dir..."
+  mkdir -p "${BINDIR}" 2>/dev/null
+  mv -vf buildrelease/ps3netsrv "${BINDIR}"/
 
-echo "Cleaning up..."
-rm -rf "${SRCDIR}"
+  echo "Cleaning up..."
+  rm -rf "${SRCDIR}"
 
-echo "All done!"
+  echo "All done!"
+  exit(0)
+fi
+
+echo "Build failed! exiting"
+exit(1)
